server:
  port: ${PORT:8080}

authorize:
  http:
    requests:
      permit-all: ${REQUESTS_PERMITTED}
      authenticated: ${REQUESTS_AUTHENTICATED}
      deny-all: ${REQUESTS_DENIED}

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${EXPIRE_KEY}

cors:
  origin-patterns: ${ORIGIN_CORS}

spring:
  application:
    name: labtrack-service
  profiles:
    active: @profileActive@
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DATABASE_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: false
  flyway:
    enabled: true
    url: ${DATABASE_URL}
    schemas: ${DATABASE_SCHEMA}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

# dev configuration
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]

# prod configuration
---
spring:
  config:
    activate:
      on-profile: prod